### ISSUE TITLE
Build failed on debian stretch with updated gdal lib

### ISSUE THREAD

**Issue by lb1c** [nmandery/batyr#9]
I have tried to compile the project on debian stretch. Because of the updated libary versions in the distribution, i also updated the install steps.
I'm using the Gitlab CI Service for building, you can see the complete build progress here:
https://gitlab.com/lb1c/batyr/-/jobs/53577003

```In file included from /builds/lb1c/batyr/src/server/db/field.h:5:0,
                 from /builds/lb1c/batyr/src/server/db/transaction.h:8,
                 from /builds/lb1c/batyr/src/server/db/connection.h:13,
                 from /builds/lb1c/batyr/src/server/worker.h:12,
                 from /builds/lb1c/batyr/src/server/worker.cpp:11:
/usr/include/gdal/ogrsf_frmts.h:245:25: note: declared here
     static void         DestroyDataSource( OGRDataSource * ) OGR_DEPRECATED("Use GDALDataset class instead");
                         ^~~~~~~~~~~~~~~~~
src/server/CMakeFiles/batyrd.dir/build.make:614: recipe for target 'src/server/CMakeFiles/batyrd.dir/worker.cpp.o' failed
make[2]: *** [src/server/CMakeFiles/batyrd.dir/worker.cpp.o] Error 1
CMakeFiles/Makefile2:269: recipe for target 'src/server/CMakeFiles/batyrd.dir/all' failed
make[1]: *** [src/server/CMakeFiles/batyrd.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
ERROR: Job failed: exit code 1```

**Comment by nmandery** [comment]
Hi,

you are using gdal version 2.1.2 which has significant changes to the version 1.x C++ API batyr was once developed for. One change would be the deprecation of the OGRDataSource class and merging it with the raster API - see http://www.gdal.org/classOGRDataSource.html .

The porting should not be too hard, but I am currently a bit short on time. I will see when I can find the time to look into this. Pull requests are always welcome :smirk:

**Comment by lb1c** [comment]
Nice work, thanks!
https://gitlab.com/lb1c/batyr/-/jobs/54129850
